/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.yamashiro0110.sample.data.jdbc;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.core.JdbcTemplate;
import org.yamashiro0110.sample.data.jdbc.model.BlogRepository;
import org.yamashiro0110.sample.data.jdbc.model.CommentRepository;

@SpringBootApplication
@Slf4j
public class SampleDataJdbcApp {
    public static void main(final String[] args) {
        SpringApplication.run(SampleDataJdbcApp.class, args);
    }

    @Autowired
    JdbcTemplate jdbcTemplate;
    @Autowired
    private BlogRepository blogRepository;
    @Autowired
    private CommentRepository commentRepository;

    void insertBlog() {
        this.jdbcTemplate.update("INSERT INTO blog (blog_id, note) VALUES (?, ?)", 1, "1st blog");
        this.jdbcTemplate.update("INSERT INTO blog (blog_id, note) VALUES (?, ?)", 2, "2st blog");
        this.jdbcTemplate.update("INSERT INTO blog (blog_id, note) VALUES (?, ?)", 3, "3st blog");
    }

    void insertComment() {
        this.jdbcTemplate.update("INSERT INTO comment (comment_id, blog_id, note) VALUES (?, ?, ?)", 1, 1, "1st comment");
        this.jdbcTemplate.update("INSERT INTO comment (comment_id, blog_id, note) VALUES (?, ?, ?)", 2, 1, "2st comment");
        this.jdbcTemplate.update("INSERT INTO comment (comment_id, blog_id, note) VALUES (?, ?, ?)", 3, 2, "3st comment");
    }

    @Bean
    CommandLineRunner insertData() {
        return args -> {
            this.insertBlog();
            this.insertComment();
        };
    }

    @Bean
    CommandLineRunner getData() {
        return args -> {
            log.info("blog:1 {}", this.blogRepository.findById(1));
            log.info("blog:2 {}", this.blogRepository.findById(2));
            log.info("blog:3 {}", this.blogRepository.findById(3));
        };
    }

}
